name: Lint

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.rst"
      - "**/*.txt"
      - "**/LICENSE*"
      - "**/.gitignore"
      - "**/docs/**"
      - "**/examples/**"
      - "**/htmlcov/**"
      - "logo.*"
      - "coverage.xml"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.rst"
      - "**/*.txt"
      - "**/LICENSE*"
      - "**/.gitignore"
      - "**/docs/**"
      - "**/examples/**"
      - "**/htmlcov/**"
      - "logo.*"
      - "coverage.xml"
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Code Quality Checks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      
      - name: Install tox
        run: python -m pip install --upgrade pip tox
      
      - name: Run linting
        run: tox -e lint
      
      - name: Run type checking
        run: tox -e check